### ISSUE TITLE
How to compile from scratch?

### ISSUE THREAD

**Issue by ylluminarious** [SrKomodo/shadowfox-updater#32]
I'm trying to make a port for this program on MacPorts, which is something we discussed in the ShadowFox repository [some months ago.](https://github.com/overdodactyl/ShadowFox/issues/180) I've been pretty swamped for months and haven't had time to do this, but while I was waiting on some things today I decided to go ahead and bite the bullet. I've tried to compile this program from scratch and I've successfully gotten it to compile, but when I try to run it, I get this fairly cryptic error (and I'm not familiar with Go):

```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc00016c100)
	/Users/my_username/go/pkg/mod/github.com/rivo/tview@v0.0.0-20180925153149-29458dad3ecc/application.go:131 +0x8b
panic(0x13180c0, 0x15c8ef0)
	/opt/local/lib/go/src/runtime/panic.go:513 +0x1b9
github.com/rivo/tview.(*TextView).Draw(0xc0000a5e10, 0x13c8820, 0xc0000ac9c0)
	/Users/my_username/go/pkg/mod/github.com/rivo/tview@v0.0.0-20180925153149-29458dad3ecc/textview.go:941 +0x14b3
github.com/rivo/tview.(*Flex).Draw(0xc0000a3770, 0x13c8820, 0xc0000ac9c0)
	/Users/my_username/go/pkg/mod/github.com/rivo/tview@v0.0.0-20180925153149-29458dad3ecc/flex.go:169 +0x295
github.com/rivo/tview.(*Application).Draw(0xc00016c100, 0x0)
	/Users/my_username/go/pkg/mod/github.com/rivo/tview@v0.0.0-20180925153149-29458dad3ecc/application.go:296 +0xdb
github.com/rivo/tview.(*Application).Run(0xc00016c100, 0x0, 0x0)
	/Users/my_username/go/pkg/mod/github.com/rivo/tview@v0.0.0-20180925153149-29458dad3ecc/application.go:137 +0xd8
main.createUI(0xc0000caf48, 0xc000094058)
	/Users/my_username/development/misc/shadowfox-updater/ui.go:147 +0x17d3
main.main()
	/Users/my_username/development/misc/shadowfox-updater/main.go:13 +0x3b
```

I'd like to know what this error means because I get an identical error message (with only the directories of the files being different) when I get this program to compile with MacPorts.

It seems like what I really need, and what would solve the problem altogether, are build instructions. I think some clear build instructions for building this program from scratch would be very helpful. Thus far, I've had to deduce how to build everything from `compiler/main.go` and then I had to deduce how to get the dependencies in `go.mod`. At this point, I think pure deduction is insufficient (and tedious).

**Comment by SrKomodo** [comment]
That error was actually a real error the program had for some reason, not a compilation error from your end, i just uploaded a fix for it. Regarding compiling, all you should have to do is run `go build` to build it for your platform, and if you want to build it for all platforms you should run this:
```
go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
go run compiler/main.go
```
Make sure you are using Go 1.11 by running `go version`.
The precise build instructions that travis-ci uses are in `.travis.yml`

**Comment by ylluminarious** [comment]
@SrKomodo Thanks a lot for the info! Glad to know that the bug was fixed. I'll try this again in the morning if possible and let you know what happens. If everything works out, I'll go ahead and close this.
