### ISSUE TITLE
Mac error: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by joshkaplan** [SrKomodo/shadowfox-updater#56]
Getting this error for v2.2. Tried the direct download (64 and 32 bit versions) and `brew` version, all give the same error when running the executable. I'm on Mac OS 10.14.6 and Firefox Quantum 68.5.0esr.

Full trace:
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.checkForUpdate(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/version.go:24 +0x2a0
main.createUI(0xc0000b1f88, 0xc000062058)
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:11 +0x37
main.main()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:13 +0x3b
```

Any ideas?  Perhaps it has something to do with having multiple profiles, or being on the esr version?

**Comment by joshkaplan** [comment]
Yeah, it's the `esr` version, which I guess means I'm on an older version of Firefox. Installing 2.1 resolved.

Might be worth mentioning in `README` or adding a compatibility chart for reference?
